### ISSUE TITLE
Constant OutOfSync warning on psmdb-db Chart

### ISSUE THREAD

**Issue by tadjik1** [percona/percona-helm-charts#256]
Hey there,
thanks a lot for your outstanding work creating and maintaining these charts.

I have a problem with psmdb-db chart - applying it with Argo results in OutOfSync problem (however, all the resources were created), at the same time everything seems ok.
Do you know what can cause this problem or how I can get rid of the warning?

 Here is my values file:
```yaml
psmdb-db:
  secrets:
    users: mongodb-secrets

  replsets:
    - name: rs0
      size: 3
      nodeSelector:
        pool-type: mongodb-spot
      tolerations:
        - key: pool-type
          operator: Equal
          value: "mongodb-spot"
          effect: NoSchedule
      resources:
        limits:
          cpu: 3000m
          memory: 13G
        requests:
          cpu: 3000m
          memory: 13G
      volumeSpec:
        pvc:
          storageClassName: premium-rwo # ssd
          resources:
            requests:
              storage: 100Gi

  backup:
    enabled: false
```

and this is how it looks like in ArgoCD UI:
<img width="1920" alt="Screenshot 2023-10-29 at 20 10 44" src="https://github.com/percona/percona-helm-charts/assets/1452895/3014d90b-d413-4c6d-a13e-d4244e8fce22">
