### ISSUE TITLE
pxc-db: backup.enabled: false leads to values.yaml overlay not being correctly merged

### ISSUE THREAD

**Issue by cjohn001** [percona/percona-helm-charts#262]
Hello together.
I am trying to customize the pxc-db chart with a myvalues.yaml. i.e.

helm install pxc-db ./pxc-db -n dev-percona -f cvalues.yaml

I am trying to do some modifications for the backup part

```
backup:
    enabled: false
    storages:
        s3-us-west:
            type: s3
            verifyTLS: false
            s3:
                bucket: dev-percona
                credentialsSecret: s3-backup-secret-working
                region: us-east-1
                endpointUrl: https://minio.example.org

```
Unfortunately, when setting backup.enabled: false, the entire backup block is not mearged into the resulting yaml.

I would expect that it is merged, because I want to be able to perform manual backups against my s3 storage. This currently seems only to work if I also enable scheduled. backups.

**Comment by spron-in** [comment]
If you don't need backups to be made on schedule, you can just leave `backup.schedule` section empty.
With it you will still be able to do manual backups.

So in your case it would be smth as follows:
```
backup:
    enabled: true
    schedule: []
    storages:
        s3-us-west:
            type: s3
            verifyTLS: false
            s3:
                bucket: dev-percona
                credentialsSecret: s3-backup-secret-working
                region: us-east-1
                endpointUrl: https://minio.example.org
```
