### ISSUE TITLE
Unable to override replica size while deploying using percona/psmdb-db

### ISSUE THREAD

**Issue by vjsrinath** [percona/percona-helm-charts#280]
Hi,

Thanks for the wonderful work on mongodb and other opensource databases.

I have been trying to get mongodb deployed in a kubernetes cluster. I am using the following values to override some values according to my use case. 
But the value set for `size` property doesn't seem to have any effect. It always tries to create three replicas. Below is the contents of `pmdb.yml`.

```yml
replsets:
  - name: rs0
    size: 2
    podSecurityContext:
      fsGroup: 1001
      runAsGroup: 1001
      runAsUser: 1001
    resources:
      limits:
        cpu: "3900m"
        memory: 14Gi
      requests:
        cpu: 2
        memory: 10Gi
```

This is how I am trying to deploy,
```sh
helm install my-db percona/psmdb-db --namespace=percona -f ./deploy/mongodb/pmdb.yml 
```

## Update:

This seems to be an issue in the operator itself. The reason I say this, the values are correctly submitted to kubernetes but the operator always is creating replicasets with 3 pods.
![image](https://github.com/percona/percona-helm-charts/assets/5001683/a57955ad-6b6d-4831-94e3-340dc5038081)
