### ISSUE TITLE
PMM: Add value to change log level

### ISSUE THREAD

**Issue by TomKeur** [percona/percona-helm-charts#298]
Hi,

Great product! I've been using using the Percona Operator for MySQL based on Percona XtraDB Cluster in combination with PMM, this is my configuration.

```yaml
pmm:
  enabled: true
  serverHost: monitoring-service
```

This is all running great, the only thing I'm noticing, the `pmm-client` container is generarting a lot of (`info`), logs.
For example:

```
time="2024-03-12T06:55:00.052+00:00" level=info msg="Sending 48 buckets." agentID=/agent_id/xxx component=agent-builtin type=qan_mysql_perf
schema_agent
```

It should be great if there a way we can change the loglevel, for example with:

```yaml
pmm:
  enabled: true
  serverHost: monitoring-service
  log:
    level: error
```
