### ISSUE TITLE
Enabling ingress causes install to fail

### ISSUE THREAD

**Issue by ofgirichardsonb** [percona/percona-helm-charts#317]
## Installation Command

`helm -n pmm install -f values.yaml pmm percona/pmm --create-namespace`

## values.yaml (ingress section only)
```
ingress:
  enabled: true
  nginxInc: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  community:
    annotations: {}
  ingressClassName: "nginx"

  hosts:
    - host: qa-pmm.olympiafinancial.ca
      paths:
        - /
  pathType: Prefix
  tls:
    - secretName: qa-pmm.olympiafinancial.ca-tls
```

## Error
```
W0403 12:29:03.606199   15978 warnings.go:70] path /server. cannot be used with pathType Prefix
Error: INSTALLATION FAILED: 1 error occurred:
	* admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "qa-pmm.olympiafinancial.ca" and path "/" is already defined in ingress percona/pmm-server
```

I will end up creating the ingress manually. But this configuration doesn't have anything wrong on its face, and there's no documentation to suggest what I am doing wrong. Please provide either documentation as to how to correctly configure the ingress, or fix the ingress creation.
