### ISSUE TITLE
pg-db chart does not support tolerations as list

### ISSUE THREAD

**Issue by networkhermit** [percona/percona-helm-charts#333]
chart version: 2.3.18

There are multiple examples that demonstrate the usage of tolerations in the values file:

https://github.com/percona/percona-helm-charts/blob/4d243856a0e272510a74d3c696b67c13d0702a5a/charts/pg-db/values.yaml#L118-L122

But the helm template does not support them well, passing a tolerations list when installing a helm release would fail:

https://github.com/percona/percona-helm-charts/blob/4d243856a0e272510a74d3c696b67c13d0702a5a/charts/pg-db/templates/cluster.yaml#L169-L175

Current workaround is passing a single tolerations map:

```yaml
  tolerations: 
    effect: NoSchedule 
    key: role 
    operator: Equal 
    value: connection-poolers
```
