### ISSUE TITLE
PMM: allow setting the resources from the chart.

### ISSUE THREAD

**Issue by MohamadTahir** [percona/percona-helm-charts#337]
currently there is no way you can set the resource for the PMM,  it would be great if we can set the pmm resources

```
pmm:
  enabled: false
  image:
    repository: percona/pmm-client
    tag: 2.41.2
  serverHost: monitoring-service
  resources:
    limits:
      cpu:
      memory:
   requests: 
      cpu:
      memory:   
```
