### ISSUE TITLE
[Feat: forcePathStyle] Add flag forcePathStyle for compatibility with Swift Storage

### ISSUE THREAD

**Issue by ellipsis-me** [percona/percona-helm-charts#347]
Hi team, I ran into a problem when tried to deploy psmdb-db chart on my cluster, because I use Swift Storage in openstack, so, Looking at the Percona MongoDB Operator CRD, I notice the CRD supports this parameter, but It was difficult to find, and including this flag on values.yaml, It Worked!
So I believe including that commented on values can be more easily found for someone else trying do deploy the Percona MongoDB in a Kubernetes Cluster running on Openstack environment.

Percona MongoDB CRD where I found the flag: https://github.com/percona/percona-server-mongodb-operator/blob/main/deploy/crd.yaml#L125-L126

It can be added into values.yaml on psmdb-db Chart: https://github.com/percona/percona-helm-charts/blob/main/charts/psmdb-db/values.yaml#L525
```yaml
minio:
  type: s3
  s3:
    bucket: MINIO-BACKUP-BUCKET-NAME-HERE
    region: us-east-1
    credentialsSecret: my-cluster-name-backup-minio
    endpointUrl: http://minio.psmdb.svc.cluster.local:9000/minio/
    prefix: ""
#   In case of use Swift storage, this flag must be set to true
    forcePathStyle: true
```
![image](https://github.com/user-attachments/assets/83bb487c-c9fe-472d-93ee-020e7bbb413e)
