### ISSUE TITLE
pg-db backup schedule not getting set

### ISSUE THREAD

**Issue by rkm4bc** [percona/percona-helm-charts#354]
Chart Name: percona/pg-db 
Chart Version 2.4.1 

When I am creating postgres cluster using above helm chart and trying to schedule backup, its getting set as empty map. Please refer the below:

```
- name: repo1
  schedules: {}
  volume:
    volumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1G
```

**Comment by rkm4bc** [comment]
Here are the pgbackrest values we are passing
```
backups:
  pgbackrest:
    image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.51-1
    global:
      repo1-retention-full-type: count
      repo1-retention-full: "1"
    manual:
      repoName: repo1
      options:
      - --type=full
    repos:
      - name: repo1
        schedules:
          full: "0 0 * * 6"
        volume:
          volumeClaimSpec:
            storageClassName: csi-rbd-sc
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
```
