### ISSUE TITLE
[Low] Deployment with ArgoCD generates warning in Persistent Storage once deployed...

### ISSUE THREAD

**Issue by LucasBrazi06** [percona/percona-helm-charts#358]
Here below the ArgoCD template:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-monitoring
spec:
  destination:
    name: in-cluster
    namespace: mongodb
  source:
    repoURL: 'https://percona.github.io/percona-helm-charts'
    chart: pmm
    targetRevision: 1.3.14
    helm:
      values: |
        storage:
          storageClassName: 'general-sc'
          size: 10Gi
        nodeSelector:
          landscape: monitoring
        tolerations:
          - key: landscape
            operator: Equal
            value: monitoring
            effect: NoSchedule
  project: e-mobility
  syncPolicy:
    automated: null
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
```

Once deployed a warning appears:

![image](https://github.com/user-attachments/assets/13378961-9fa4-43dd-8689-add296303247)

And when I display the deployed manifest (1) and the desired one (2) I have this diff that generates the warning:

![image](https://github.com/user-attachments/assets/0d03f2a6-7d1c-4fc1-9016-71aaecac0202)

Despite this warning, PMM is working fine and the PVC is bound correctly, it's just for removing the warning.

Thanks.
Serge.
