### ISSUE TITLE
PGBouncer database configuration is not parsed

### ISSUE THREAD

**Issue by Alkiimista** [percona/percona-helm-charts#372]
Hello, it doesn't seem like the `pg-operator` takes into account the pgbouncer configuration that you can configure in the `pg-db` helmchart

```yaml
proxy:
  pgBouncer:
    config:
      databases:
        '*': host=test-database-pg-db-primary.test-namespace port=5432
```

According to the code found [here](https://github.com/percona/percona-postgresql-operator/blob/df3cf346e80b3d4472259f1a902c2865207336b8/internal/pgbouncer/config.go#L163) it should parse the config section and overwrite / replace the database section in pgbouncer.ini

I'm making use of the following helmchart versions:
- pg-operator@2.4.1
- pg-db@2.4.1
