### ISSUE TITLE
Secrets (charts/pxc-db/templates/cluster-ssl-secret.yaml) are regenerated even if they exist

### ISSUE THREAD

**Issue by olegsmetanin** [percona/percona-helm-charts#574]
On every depolyment
```
cat <<EOF | helm diff upgrade perconadb-dev percona/pxc-db --install -n perconadb-dev --version 1.17.1 -f -
pxc:
  size: 1
  persistence:
    storageClass: local-path
    size: 8Gi
  affinity:
    antiAffinityTopologyKey: "none"
haproxy:
  size: 1
  affinity:
    antiAffinityTopologyKey: "none"
## Allows to have less than 3 pcx and ha-proxy
unsafeFlags:
  pxcSize: true
  proxySize: true
EOF
```

I see secret changes:
```
perconadb-dev, perconadb-dev-pxc-db-ssl, Secret (v1) has changed:
  # Source: pxc-db/templates/cluster-ssl-secret.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      helm.sh/resource-policy: keep
    labels:
      app.kubernetes.io/instance: perconadb-dev
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: pxc-db
      app.kubernetes.io/version: 1.17.0
      helm.sh/chart: pxc-db-1.17.1
    name: perconadb-dev-pxc-db-ssl
    namespace: perconadb-dev
  data:
-   ca.crt: '-------- # (1168 bytes)'
-   tls.crt: '-------- # (1306 bytes)'
-   tls.key: '-------- # (1675 bytes)'
+   ca.crt: '++++++++ # (1168 bytes)'
+   tls.crt: '++++++++ # (1310 bytes)'
+   tls.key: '++++++++ # (1675 bytes)'
  type: kubernetes.io/tls

perconadb-dev, perconadb-dev-pxc-db-ssl-internal, Secret (v1) has changed:
  # Source: pxc-db/templates/cluster-ssl-secret.yaml
  apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      helm.sh/resource-policy: keep
    labels:
      app.kubernetes.io/instance: perconadb-dev
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: pxc-db
      app.kubernetes.io/version: 1.17.0
      helm.sh/chart: pxc-db-1.17.1
    name: perconadb-dev-pxc-db-ssl-internal
    namespace: perconadb-dev
  data:
-   ca.crt: '-------- # (1168 bytes)'
-   tls.crt: '-------- # (1671 bytes)'
-   tls.key: '-------- # (1675 bytes)'
+   ca.crt: '++++++++ # (1168 bytes)'
+   tls.crt: '++++++++ # (1671 bytes)'
+   tls.key: '++++++++ # (1675 bytes)'
  type: kubernetes.io/tls
```
What is not expected based on implementation in https://github.com/percona/percona-helm-charts/blob/main/charts/pxc-db/templates/cluster-ssl-secret.yaml#L21. If the secret already exists, it should be reused.

Is this the issue with the helm lookup?

**Comment by olegsmetanin** [comment]
I suggest not generating a Secret at all if it already exists:
https://github.com/percona/percona-helm-charts/blob/main/charts/pxc-db/templates/cluster-ssl-secret.yaml#L35
```
{{- if and (not (hasKey .Values.secrets.tls "cluster")) (not $existingCert) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $nameDB }}-ssl
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
{{ include "pxc-database.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $caCert }}
  tls.crt: {{ $tlsCert }}
  tls.key: {{ $tlsKey }}
{{- end -}}
```
